// ============================================================
// EXERCISES — The workout content database
// Each exercise has metadata used by the workout engine.
// easierSwap/harderSwap IDs let the engine chain modifications.
// equipment: 'none' | 'chair' | 'wall' | 'band' | 'dumbbell'
// category: 'strength' | 'cardio' | 'mobility' | 'warmup' | 'cooldown'
//
// FORM GUIDE FIELDS (new):
//   steps[]  — numbered instructions for performing the exercise
//   tips[]   — common mistakes & form cues
//   breathe  — breathing pattern
// ============================================================

export const EXERCISES = [
  // ================================================================
  //  LEGS
  // ================================================================
  {
    id: 'jump-squats',
    name: 'Jump Squats',
    duration: 45,
    intensity: 8,
    muscle: 'Legs',
    icon: '🦵',
    equipment: 'none',
    category: 'strength',
    description: 'Squat down, then explode upward into a jump.',
    easierSwap: 'bodyweight-squats',
    harderSwap: 'squat-tuck-jumps',
    steps: [
      'Stand with feet shoulder-width apart, toes slightly out.',
      'Lower into a squat — hips back, chest up, thighs parallel to floor.',
      'Explode upward, pushing through your heels and balls of feet.',
      'Jump as high as you can, extending fully at the top.',
      'Land softly with bent knees, absorbing the impact.',
      'Immediately lower into the next squat.',
    ],
    tips: [
      'Land quietly — if you hear a loud thud, bend your knees more on landing.',
      'Keep your chest up throughout — don\'t fold forward.',
      'Push your knees out over your toes, don\'t let them cave in.',
    ],
    breathe: 'Inhale as you squat down. Exhale sharply as you jump up.',
  },
  {
    id: 'bodyweight-squats',
    name: 'Bodyweight Squats',
    duration: 45,
    intensity: 5,
    muscle: 'Legs',
    icon: '🦵',
    equipment: 'none',
    category: 'strength',
    description: 'Standard squat without the jump.',
    easierSwap: 'wall-sit',
    harderSwap: 'jump-squats',
    steps: [
      'Stand with feet shoulder-width apart, toes slightly turned out.',
      'Extend arms forward for balance, or hold them at your chest.',
      'Push your hips back and bend your knees, like sitting in a chair.',
      'Lower until thighs are parallel to the floor (or as low as comfortable).',
      'Push through your heels to stand back up.',
      'Squeeze your glutes at the top.',
    ],
    tips: [
      'Keep your weight in your heels — you should be able to wiggle your toes.',
      'Don\'t let your knees collapse inward.',
      'Keep your core braced and chest proud throughout.',
    ],
    breathe: 'Inhale on the way down. Exhale as you push back up.',
  },
  {
    id: 'wall-sit',
    name: 'Wall Sit',
    duration: 40,
    intensity: 4,
    muscle: 'Legs',
    icon: '🦵',
    equipment: 'wall',
    category: 'strength',
    description: 'Sit against a wall with knees at 90°. Hold.',
    easierSwap: null,
    harderSwap: 'bodyweight-squats',
    steps: [
      'Stand with your back flat against a wall.',
      'Walk your feet out about 2 feet from the wall.',
      'Slide down the wall until your thighs are parallel to the floor.',
      'Your knees should be at a 90° angle, directly above your ankles.',
      'Press your lower back into the wall.',
      'Hold this position for the full duration.',
    ],
    tips: [
      'Don\'t let your knees go past your toes.',
      'Keep your back flat — don\'t arch away from the wall.',
      'If it\'s too hard, don\'t slide down as far.',
    ],
    breathe: 'Breathe steadily throughout. Don\'t hold your breath — that makes it harder.',
  },
  {
    id: 'squat-tuck-jumps',
    name: 'Squat Tuck Jumps',
    duration: 40,
    intensity: 10,
    muscle: 'Legs',
    icon: '🦵',
    equipment: 'none',
    category: 'strength',
    description: 'Squat, then jump and tuck knees to chest.',
    easierSwap: 'jump-squats',
    harderSwap: null,
    steps: [
      'Start in a squat position — hips back, chest up.',
      'Explode upward as high as possible.',
      'At the peak of your jump, tuck both knees toward your chest.',
      'Grab your shins briefly if you can.',
      'Release and extend your legs for landing.',
      'Land softly with bent knees and go straight into the next rep.',
    ],
    tips: [
      'This is advanced — master jump squats first.',
      'Focus on height before the tuck. Jump UP, then tuck.',
      'Land as quietly as possible.',
    ],
    breathe: 'Sharp exhale as you jump. Quick inhale on landing.',
  },
  {
    id: 'lunges',
    name: 'Lunges',
    duration: 40,
    intensity: 7,
    muscle: 'Legs',
    icon: '🦿',
    equipment: 'none',
    category: 'strength',
    description: 'Step forward, lower until both knees are at 90°.',
    easierSwap: 'step-touches',
    harderSwap: 'jump-lunges',
    steps: [
      'Stand tall with feet hip-width apart.',
      'Take a big step forward with one leg.',
      'Lower your body until both knees are at 90° angles.',
      'Your back knee should hover just above the floor.',
      'Push through your front heel to return to standing.',
      'Alternate legs with each rep.',
    ],
    tips: [
      'Keep your torso upright — don\'t lean forward.',
      'Your front knee should stay above your ankle, not past your toes.',
      'Take a big enough step — too short puts stress on your knee.',
    ],
    breathe: 'Inhale as you step forward and lower. Exhale as you push back up.',
  },
  {
    id: 'step-touches',
    name: 'Step Touches',
    duration: 40,
    intensity: 3,
    muscle: 'Legs',
    icon: '🦿',
    equipment: 'none',
    category: 'strength',
    description: 'Step side to side, touching each foot.',
    easierSwap: null,
    harderSwap: 'lunges',
    steps: [
      'Stand with feet together, knees slightly bent.',
      'Step your right foot out to the right.',
      'Bring your left foot to meet it, tapping the ground.',
      'Now step your left foot out to the left.',
      'Bring your right foot to meet it.',
      'Continue alternating at a comfortable pace.',
    ],
    tips: [
      'Stay light on your feet with a slight bounce.',
      'Swing your arms naturally for rhythm.',
      'Speed up gradually as you warm up.',
    ],
    breathe: 'Breathe naturally and rhythmically.',
  },
  {
    id: 'jump-lunges',
    name: 'Jump Lunges',
    duration: 35,
    intensity: 9,
    muscle: 'Legs',
    icon: '🦿',
    equipment: 'none',
    category: 'strength',
    description: 'Lunge then jump and switch legs mid-air.',
    easierSwap: 'lunges',
    harderSwap: null,
    steps: [
      'Start in a lunge position — one foot forward, one back.',
      'Lower into the lunge until both knees are near 90°.',
      'Explode upward, jumping off both feet.',
      'Switch legs in the air.',
      'Land softly in a lunge with the opposite leg forward.',
      'Immediately drop into the next lunge and repeat.',
    ],
    tips: [
      'Use your arms for momentum — swing them as you jump.',
      'Land toe-to-heel for shock absorption.',
      'If balance is hard, do alternating lunges without the jump first.',
    ],
    breathe: 'Exhale as you jump. Inhale as you land and lower.',
  },
  {
    id: 'goblet-squats',
    name: 'Goblet Squats',
    duration: 45,
    intensity: 7,
    muscle: 'Legs',
    icon: '🦵',
    equipment: 'dumbbell',
    category: 'strength',
    description: 'Hold a dumbbell at your chest and squat deep.',
    easierSwap: 'bodyweight-squats',
    harderSwap: 'dumbbell-squat-press',
    steps: [
      'Hold a dumbbell vertically at your chest, cupping one end with both hands.',
      'Stand with feet slightly wider than shoulder-width, toes out.',
      'Keeping the weight close to your chest, push hips back and squat down.',
      'Go as deep as you can — elbows should track inside your knees.',
      'Push through your heels to stand back up.',
      'Squeeze glutes at the top.',
    ],
    tips: [
      'The weight helps you stay upright — use it as a counterbalance.',
      'Keep your elbows pointing down, not flaring out.',
      'Go deeper than a bodyweight squat — the weight makes it easier to hit depth.',
    ],
    breathe: 'Inhale as you lower. Exhale forcefully as you drive up.',
  },
  {
    id: 'dumbbell-squat-press',
    name: 'Squat to Press',
    duration: 45,
    intensity: 9,
    muscle: 'Legs',
    icon: '🦵',
    equipment: 'dumbbell',
    category: 'strength',
    description: 'Goblet squat, then press the dumbbell overhead at the top.',
    easierSwap: 'goblet-squats',
    harderSwap: null,
    steps: [
      'Hold a dumbbell at chest height with both hands.',
      'Squat down — hips back, chest up, go to parallel or below.',
      'Drive up through your heels explosively.',
      'As you reach the top, press the dumbbell overhead.',
      'Lock out your arms fully, biceps near ears.',
      'Lower the weight back to chest height as you descend into the next squat.',
    ],
    tips: [
      'Use the momentum from the squat to help press the weight overhead.',
      'This is a full-body movement — stay controlled throughout.',
      'Start lighter than you think.',
    ],
    breathe: 'Inhale going down. Exhale as you stand and press.',
  },
  {
    id: 'calf-raises',
    name: 'Calf Raises',
    duration: 40,
    intensity: 4,
    muscle: 'Legs',
    icon: '🦵',
    equipment: 'none',
    category: 'strength',
    description: 'Rise onto your toes, squeeze at the top, lower slowly.',
    easierSwap: null,
    harderSwap: 'single-leg-calf-raises',
    steps: [
      'Stand with feet hip-width apart near a wall for balance if needed.',
      'Slowly rise up onto the balls of your feet.',
      'Squeeze your calves hard at the top.',
      'Hold for 1-2 seconds.',
      'Lower slowly back down — take 2-3 seconds.',
      'Let your heels lightly touch the floor, then go again.',
    ],
    tips: [
      'The slow lower is where the magic happens — don\'t just drop down.',
      'Stand on a step edge for extra range of motion.',
      'Point toes straight, slightly in, or slightly out to hit different calf areas.',
    ],
    breathe: 'Exhale as you rise. Inhale as you lower.',
  },
  {
    id: 'single-leg-calf-raises',
    name: 'Single-Leg Calf Raises',
    duration: 40,
    intensity: 6,
    muscle: 'Legs',
    icon: '🦵',
    equipment: 'none',
    category: 'strength',
    description: 'Calf raise on one leg at a time. Hold a wall for balance.',
    easierSwap: 'calf-raises',
    harderSwap: null,
    steps: [
      'Stand on one foot near a wall for balance.',
      'Tuck the other foot behind your standing ankle.',
      'Rise up onto the ball of your standing foot.',
      'Squeeze at the top for 1-2 seconds.',
      'Lower slowly and with control.',
      'Complete all reps on one side, then switch.',
    ],
    tips: [
      'Use the wall only for balance, not to push yourself up.',
      'Keep your standing leg straight but not locked.',
      'If too hard, do double-leg calf raises instead.',
    ],
    breathe: 'Exhale going up. Inhale coming down.',
  },

  // ================================================================
  //  CHEST
  // ================================================================
  {
    id: 'push-ups',
    name: 'Push-Ups',
    duration: 40,
    intensity: 7,
    muscle: 'Chest',
    icon: '💪',
    equipment: 'none',
    category: 'strength',
    description: 'Standard push-up. Keep your core tight.',
    easierSwap: 'knee-push-ups',
    harderSwap: 'diamond-push-ups',
    steps: [
      'Start in a high plank — hands slightly wider than shoulders.',
      'Body forms a straight line from head to heels.',
      'Bend your elbows and lower your chest toward the floor.',
      'Go until your chest is a fist-width from the ground.',
      'Push back up to the starting position.',
      'Keep your core engaged the entire time.',
    ],
    tips: [
      'Don\'t flare your elbows out to 90° — keep them at about 45°.',
      'Squeeze your glutes to keep your hips from sagging.',
      'Look slightly ahead of your hands, not straight down.',
    ],
    breathe: 'Inhale as you lower. Exhale as you push up.',
  },
  {
    id: 'knee-push-ups',
    name: 'Knee Push-Ups',
    duration: 40,
    intensity: 4,
    muscle: 'Chest',
    icon: '💪',
    equipment: 'none',
    category: 'strength',
    description: 'Push-up from your knees.',
    easierSwap: 'wall-push-ups',
    harderSwap: 'push-ups',
    steps: [
      'Start on all fours, then walk your hands forward.',
      'Lower your hips so your body is straight from knees to head.',
      'Cross your ankles behind you.',
      'Bend your elbows and lower your chest toward the floor.',
      'Push back up to the starting position.',
    ],
    tips: [
      'Don\'t stick your butt up — keep a straight line from knees to shoulders.',
      'Same elbow angle as regular push-ups — about 45°.',
      'This is a real exercise, not a "cheat" — own it.',
    ],
    breathe: 'Inhale down. Exhale up.',
  },
  {
    id: 'diamond-push-ups',
    name: 'Diamond Push-Ups',
    duration: 35,
    intensity: 9,
    muscle: 'Chest',
    icon: '💪',
    equipment: 'none',
    category: 'strength',
    description: 'Hands form a diamond. Targets triceps hard.',
    easierSwap: 'push-ups',
    harderSwap: null,
    steps: [
      'Start in push-up position.',
      'Bring your hands together under your chest.',
      'Touch thumbs and index fingers to form a diamond shape.',
      'Lower your chest to your hands, keeping elbows close to your body.',
      'Push back up, squeezing your triceps at the top.',
    ],
    tips: [
      'Keep elbows tucked tight to your sides.',
      'If wrists hurt, widen the diamond slightly.',
      'Go to knees if you can\'t maintain form.',
    ],
    breathe: 'Inhale down. Exhale up.',
  },
  {
    id: 'wide-push-ups',
    name: 'Wide Push-Ups',
    duration: 40,
    intensity: 7,
    muscle: 'Chest',
    icon: '💪',
    equipment: 'none',
    category: 'strength',
    description: 'Push-ups with hands wider than shoulders. More chest focus.',
    easierSwap: 'knee-push-ups',
    harderSwap: 'decline-push-ups',
    steps: [
      'Start in push-up position.',
      'Walk your hands out wider — about 1.5x shoulder width.',
      'Angle your fingers outward slightly.',
      'Lower your chest toward the floor.',
      'Push back up, squeezing your chest.',
    ],
    tips: [
      'Don\'t go TOO wide — it strains your shoulders.',
      'You won\'t go as low as a standard push-up, and that\'s fine.',
      'Focus on feeling the stretch across your chest at the bottom.',
    ],
    breathe: 'Inhale as you lower. Exhale as you press up.',
  },
  {
    id: 'decline-push-ups',
    name: 'Decline Push-Ups',
    duration: 35,
    intensity: 8,
    muscle: 'Chest',
    icon: '💪',
    equipment: 'chair',
    category: 'strength',
    description: 'Feet elevated on a chair. Hits upper chest and shoulders.',
    easierSwap: 'wide-push-ups',
    harderSwap: null,
    steps: [
      'Place your feet on a chair, bench, or sturdy elevated surface.',
      'Hands on the floor, slightly wider than shoulder-width.',
      'Keep your body in a straight line — don\'t sag or pike.',
      'Lower your chest toward the floor.',
      'Push back up.',
    ],
    tips: [
      'Make sure the chair is stable and won\'t slide.',
      'The higher your feet, the harder it gets.',
      'Keep your core very tight — this is easy to lose form on.',
    ],
    breathe: 'Inhale down. Exhale up.',
  },
  {
    id: 'dumbbell-chest-press',
    name: 'Floor Chest Press',
    duration: 45,
    intensity: 7,
    muscle: 'Chest',
    icon: '💪',
    equipment: 'dumbbell',
    category: 'strength',
    description: 'Lie on your back, press dumbbells straight up.',
    easierSwap: 'knee-push-ups',
    harderSwap: 'dumbbell-chest-fly',
    steps: [
      'Lie on your back with knees bent, feet flat on the floor.',
      'Hold a dumbbell in each hand at chest level, palms facing your feet.',
      'Press the dumbbells straight up until arms are extended.',
      'Pause briefly at the top.',
      'Lower slowly until your upper arms touch the floor.',
      'Press back up and repeat.',
    ],
    tips: [
      'Your elbows stop at the floor — this limits range but protects shoulders.',
      'Keep your back flat, don\'t arch excessively.',
      'Drive through your chest, not just your arms.',
    ],
    breathe: 'Inhale as you lower. Exhale as you press up.',
  },
  {
    id: 'dumbbell-chest-fly',
    name: 'Floor Chest Fly',
    duration: 45,
    intensity: 8,
    muscle: 'Chest',
    icon: '💪',
    equipment: 'dumbbell',
    category: 'strength',
    description: 'Lie on your back, arc dumbbells out wide then squeeze together.',
    easierSwap: 'dumbbell-chest-press',
    harderSwap: null,
    steps: [
      'Lie on your back with dumbbells held above your chest, palms facing each other.',
      'Keep a slight bend in your elbows throughout.',
      'Open your arms wide, lowering the dumbbells in an arc.',
      'Stop when your upper arms touch the floor.',
      'Squeeze your chest to bring the dumbbells back together.',
    ],
    tips: [
      'Think "hugging a tree" — arc motion, not a press.',
      'Keep the bend in your elbows constant.',
      'Use lighter weight than chest press — this is an isolation move.',
    ],
    breathe: 'Inhale as you open. Exhale as you squeeze together.',
  },

  // ================================================================
  //  CORE
  // ================================================================
  {
    id: 'mountain-climbers',
    name: 'Mountain Climbers',
    duration: 30,
    intensity: 9,
    muscle: 'Core',
    icon: '🏔️',
    equipment: 'none',
    category: 'strength',
    description: 'Plank position, drive knees to chest alternately.',
    easierSwap: 'slow-climbers',
    harderSwap: 'spider-climbers',
    steps: [
      'Start in a high plank position — hands under shoulders.',
      'Drive your right knee toward your chest.',
      'Quickly switch, extending right leg back while driving left knee in.',
      'Continue alternating as fast as you can maintain form.',
      'Keep your hips level — don\'t let them bounce up and down.',
    ],
    tips: [
      'Your hips should stay at the same height the whole time.',
      'Drive knees straight forward, not out to the sides.',
      'Think "running in plank" — fast but controlled.',
    ],
    breathe: 'Breathe rhythmically — exhale every 2-3 knee drives.',
  },
  {
    id: 'slow-climbers',
    name: 'Slow Climbers',
    duration: 30,
    intensity: 6,
    muscle: 'Core',
    icon: '🏔️',
    equipment: 'none',
    category: 'strength',
    description: 'Mountain climbers at half speed. Focus on form.',
    easierSwap: 'knee-plank',
    harderSwap: 'mountain-climbers',
    steps: [
      'Start in a high plank.',
      'Slowly bring your right knee toward your chest.',
      'Hold for a beat, feeling your core engage.',
      'Return it and bring the left knee in.',
      'Move at about half the speed of regular mountain climbers.',
    ],
    tips: [
      'Focus on the squeeze — feel your abs working with each knee drive.',
      'Keep shoulders stacked over wrists.',
      'This is about control, not speed.',
    ],
    breathe: 'Exhale as each knee comes forward. Inhale as it goes back.',
  },
  {
    id: 'spider-climbers',
    name: 'Spider Climbers',
    duration: 30,
    intensity: 10,
    muscle: 'Core',
    icon: '🏔️',
    equipment: 'none',
    category: 'strength',
    description: 'Mountain climbers but knees go to elbows.',
    easierSwap: 'mountain-climbers',
    harderSwap: null,
    steps: [
      'Start in a high plank.',
      'Drive your right knee toward your RIGHT elbow (to the outside).',
      'Return and drive left knee to LEFT elbow.',
      'Alternate at a steady pace.',
    ],
    tips: [
      'You\'ll feel this in your obliques way more than regular climbers.',
      'Keep your hips from rotating too much.',
      'Slow down if your form breaks.',
    ],
    breathe: 'Exhale as the knee reaches the elbow.',
  },
  {
    id: 'plank-hold',
    name: 'Plank Hold',
    duration: 45,
    intensity: 6,
    muscle: 'Core',
    icon: '🧱',
    equipment: 'none',
    category: 'strength',
    description: 'Hold a straight-arm or forearm plank.',
    easierSwap: 'knee-plank',
    harderSwap: 'plank-shoulder-taps',
    steps: [
      'Place forearms on the floor, elbows directly under shoulders.',
      'Extend your legs back, toes on the ground.',
      'Your body should form a straight line from head to heels.',
      'Engage your core by pulling your belly button toward your spine.',
      'Hold this position without letting your hips sag or rise.',
    ],
    tips: [
      'Squeeze your glutes — this takes pressure off your lower back.',
      'Don\'t look up — keep your neck neutral, gaze at the floor.',
      'If your back starts to sag, take a break. Bad form > longer hold.',
    ],
    breathe: 'Breathe steadily and deeply. Never hold your breath.',
  },
  {
    id: 'knee-plank',
    name: 'Knee Plank',
    duration: 45,
    intensity: 3,
    muscle: 'Core',
    icon: '🧱',
    equipment: 'none',
    category: 'strength',
    description: 'Plank from your knees.',
    easierSwap: null,
    harderSwap: 'plank-hold',
    steps: [
      'Place forearms on the floor, elbows under shoulders.',
      'Keep your knees on the ground.',
      'Form a straight line from knees to head.',
      'Engage your core and hold.',
    ],
    tips: [
      'Don\'t let your hips drop or pike up.',
      'This builds the strength you need for a full plank.',
      'Place a folded towel under your knees for comfort.',
    ],
    breathe: 'Breathe normally throughout. Steady and calm.',
  },
  {
    id: 'plank-shoulder-taps',
    name: 'Plank Shoulder Taps',
    duration: 40,
    intensity: 8,
    muscle: 'Core',
    icon: '🧱',
    equipment: 'none',
    category: 'strength',
    description: 'In plank, alternate tapping opposite shoulder.',
    easierSwap: 'plank-hold',
    harderSwap: null,
    steps: [
      'Start in a high plank (hands, not forearms).',
      'Widen your feet slightly for stability.',
      'Lift your right hand and tap your left shoulder.',
      'Place it back down. Lift your left hand, tap right shoulder.',
      'Alternate while keeping your hips as still as possible.',
    ],
    tips: [
      'The goal is ZERO hip rotation. Wider feet help.',
      'Go slow — speed makes you sway.',
      'Brace your core like someone is about to poke your stomach.',
    ],
    breathe: 'Exhale on each tap. Inhale between.',
  },
  {
    id: 'bicycle-crunches',
    name: 'Bicycle Crunches',
    duration: 40,
    intensity: 7,
    muscle: 'Core',
    icon: '🔥',
    equipment: 'none',
    category: 'strength',
    description: 'Lie on your back, alternate elbow to opposite knee.',
    easierSwap: 'dead-bugs',
    harderSwap: 'v-ups',
    steps: [
      'Lie on your back, hands behind your head.',
      'Lift your shoulders off the ground.',
      'Bring your right elbow toward your left knee while extending right leg.',
      'Switch — left elbow to right knee, extending left leg.',
      'Pedal in a smooth, controlled motion.',
    ],
    tips: [
      'Don\'t pull on your neck — fingers light behind your head.',
      'Twist from your ribcage, not just your elbows.',
      'Keep your lower back pressed into the floor.',
    ],
    breathe: 'Exhale on each twist.',
  },
  {
    id: 'dead-bugs',
    name: 'Dead Bugs',
    duration: 40,
    intensity: 4,
    muscle: 'Core',
    icon: '🐛',
    equipment: 'none',
    category: 'strength',
    description: 'Lie on your back, extend opposite arm and leg while bracing core.',
    easierSwap: null,
    harderSwap: 'bicycle-crunches',
    steps: [
      'Lie on your back, arms reaching toward the ceiling.',
      'Lift your legs to tabletop — knees over hips, shins parallel to floor.',
      'Press your lower back into the floor (this is key).',
      'Slowly extend your right arm overhead and left leg out straight.',
      'Return to start. Switch — left arm, right leg.',
      'Move slowly and with full control.',
    ],
    tips: [
      'Your lower back MUST stay flat on the floor. If it arches, don\'t extend as far.',
      'This looks easy but is incredibly effective when done right.',
      'Go slower than you think you need to.',
    ],
    breathe: 'Exhale as you extend. Inhale as you return.',
  },
  {
    id: 'v-ups',
    name: 'V-Ups',
    duration: 35,
    intensity: 9,
    muscle: 'Core',
    icon: '🔥',
    equipment: 'none',
    category: 'strength',
    description: 'Lie flat, simultaneously lift legs and torso to touch toes.',
    easierSwap: 'bicycle-crunches',
    harderSwap: null,
    steps: [
      'Lie flat on your back, arms extended overhead.',
      'Simultaneously lift your legs and upper body off the floor.',
      'Reach your hands toward your toes, forming a V shape.',
      'Touch your toes (or shins) at the top.',
      'Lower everything back down with control.',
    ],
    tips: [
      'Keep your legs as straight as possible.',
      'If you can\'t reach your toes, reach for your shins.',
      'Don\'t use momentum — if you\'re swinging, slow down.',
    ],
    breathe: 'Exhale as you crunch up. Inhale as you lower.',
  },
  {
    id: 'russian-twists',
    name: 'Russian Twists',
    duration: 40,
    intensity: 7,
    muscle: 'Core',
    icon: '🔥',
    equipment: 'none',
    category: 'strength',
    description: 'Seated, lean back slightly, rotate side to side.',
    easierSwap: 'seated-twists',
    harderSwap: 'weighted-russian-twists',
    steps: [
      'Sit on the floor with knees bent, feet flat.',
      'Lean back about 45° — keep your back straight, not rounded.',
      'Lift your feet slightly off the floor (or keep them down if needed).',
      'Clasp your hands together at chest level.',
      'Rotate your torso to the right, then to the left.',
      'Each side is one rep.',
    ],
    tips: [
      'Rotate from your ribcage, not just your arms.',
      'Keep your chest lifted — don\'t collapse forward.',
      'Feet down is easier; feet up is harder.',
    ],
    breathe: 'Exhale on each rotation.',
  },
  {
    id: 'seated-twists',
    name: 'Seated Twists',
    duration: 40,
    intensity: 3,
    muscle: 'Core',
    icon: '🔥',
    equipment: 'none',
    category: 'strength',
    description: 'Seated twist with feet on the ground. Gentle oblique work.',
    easierSwap: null,
    harderSwap: 'russian-twists',
    steps: [
      'Sit on the floor with knees bent, feet flat on the ground.',
      'Lean back slightly, keeping your back straight.',
      'Hold your hands together at your chest.',
      'Gently rotate your torso to one side, then the other.',
      'Keep your feet planted throughout.',
    ],
    tips: [
      'This is a gentle version — focus on the stretch and squeeze.',
      'Keep your spine tall, don\'t slouch.',
      'Move at a comfortable pace.',
    ],
    breathe: 'Exhale gently as you twist each direction.',
  },
  {
    id: 'weighted-russian-twists',
    name: 'Weighted Russian Twists',
    duration: 40,
    intensity: 9,
    muscle: 'Core',
    icon: '🔥',
    equipment: 'dumbbell',
    category: 'strength',
    description: 'Russian twists holding a dumbbell for extra resistance.',
    easierSwap: 'russian-twists',
    harderSwap: null,
    steps: [
      'Sit with knees bent, feet off the floor, leaning back 45°.',
      'Hold a dumbbell with both hands at chest level.',
      'Rotate your torso to touch the dumbbell to the floor on your right.',
      'Rotate to touch it on your left.',
      'Keep your feet elevated and core braced throughout.',
    ],
    tips: [
      'Start with a light weight — this is harder than it looks.',
      'Control the weight, don\'t let momentum take over.',
      'Touch the weight to the floor gently, don\'t slam it.',
    ],
    breathe: 'Exhale on each rotation.',
  },

  // ================================================================
  //  BACK
  // ================================================================
  {
    id: 'supermans',
    name: 'Supermans',
    duration: 40,
    intensity: 5,
    muscle: 'Back',
    icon: '🦸',
    equipment: 'none',
    category: 'strength',
    description: 'Lie face down, lift arms and legs off the ground. Squeeze your back.',
    easierSwap: 'bird-dogs',
    harderSwap: 'superman-pulses',
    steps: [
      'Lie face down with arms extended overhead.',
      'Simultaneously lift your arms, chest, and legs off the floor.',
      'Squeeze your lower back and glutes at the top.',
      'Hold for 2-3 seconds.',
      'Lower everything back down with control.',
    ],
    tips: [
      'Don\'t crank your neck up — keep it neutral, looking at the floor.',
      'Think about lifting with your BACK, not your arms.',
      'Even a small lift off the floor counts — you don\'t need huge range.',
    ],
    breathe: 'Inhale at the bottom. Exhale as you lift up.',
  },
  {
    id: 'bird-dogs',
    name: 'Bird Dogs',
    duration: 40,
    intensity: 3,
    muscle: 'Back',
    icon: '🐕',
    equipment: 'none',
    category: 'strength',
    description: 'On all fours, extend opposite arm and leg. Hold briefly.',
    easierSwap: null,
    harderSwap: 'supermans',
    steps: [
      'Start on all fours — hands under shoulders, knees under hips.',
      'Extend your right arm forward and left leg backward simultaneously.',
      'Form a straight line from fingertips to toes.',
      'Hold for 2-3 seconds.',
      'Return to start. Switch sides.',
    ],
    tips: [
      'Keep your hips level — don\'t let them tilt to one side.',
      'Imagine balancing a glass of water on your lower back.',
      'Move slowly and deliberately.',
    ],
    breathe: 'Exhale as you extend. Inhale as you return.',
  },
  {
    id: 'superman-pulses',
    name: 'Superman Pulses',
    duration: 35,
    intensity: 7,
    muscle: 'Back',
    icon: '🦸',
    equipment: 'none',
    category: 'strength',
    description: 'Hold superman position and pulse arms up and down.',
    easierSwap: 'supermans',
    harderSwap: 'reverse-snow-angels',
    steps: [
      'Get into the superman position — everything lifted.',
      'Hold the lift and pulse your arms up and down in small movements.',
      'Keep your legs lifted and still.',
      'Continue pulsing for the full duration.',
    ],
    tips: [
      'Small, controlled pulses — not big swings.',
      'Keep breathing throughout.',
      'Your back should be engaged the entire time.',
    ],
    breathe: 'Breathe steadily — don\'t hold your breath.',
  },
  {
    id: 'reverse-snow-angels',
    name: 'Reverse Snow Angels',
    duration: 40,
    intensity: 8,
    muscle: 'Back',
    icon: '👼',
    equipment: 'none',
    category: 'strength',
    description: 'Lie face down, sweep arms from hips to overhead in an arc.',
    easierSwap: 'superman-pulses',
    harderSwap: null,
    steps: [
      'Lie face down with arms at your sides, palms facing down.',
      'Lift your chest, arms, and legs slightly off the floor.',
      'Sweep your arms in a wide arc from your hips to overhead.',
      'Touch your thumbs together above your head.',
      'Sweep back down to your hips.',
      'Keep everything lifted the entire time.',
    ],
    tips: [
      'Stay lifted — your chest and legs don\'t touch the floor until you\'re done.',
      'Go slow — the arc is where the work happens.',
      'Squeeze your shoulder blades together as arms sweep overhead.',
    ],
    breathe: 'Inhale as arms go overhead. Exhale as they sweep back.',
  },
  {
    id: 'dumbbell-rows',
    name: 'Dumbbell Rows',
    duration: 45,
    intensity: 7,
    muscle: 'Back',
    icon: '🏋️',
    equipment: 'dumbbell',
    category: 'strength',
    description: 'Hinge forward, pull dumbbell to your hip. Squeeze your shoulder blade.',
    easierSwap: 'supermans',
    harderSwap: 'renegade-rows',
    steps: [
      'Hold a dumbbell in one hand.',
      'Hinge forward at the hips about 45° — flat back.',
      'Let the dumbbell hang straight down.',
      'Pull the dumbbell to your hip, leading with your elbow.',
      'Squeeze your shoulder blade at the top.',
      'Lower with control. Complete all reps, then switch sides.',
    ],
    tips: [
      'Think "elbow to ceiling" — pull with your back, not your bicep.',
      'Keep your back flat — no rounding.',
      'Brace your free hand on a chair or your knee for stability.',
    ],
    breathe: 'Exhale as you row up. Inhale as you lower.',
  },
  {
    id: 'renegade-rows',
    name: 'Renegade Rows',
    duration: 40,
    intensity: 9,
    muscle: 'Back',
    icon: '🏋️',
    equipment: 'dumbbell',
    category: 'strength',
    description: 'Plank on dumbbells, row one at a time. Core and back killer.',
    easierSwap: 'dumbbell-rows',
    harderSwap: null,
    steps: [
      'Place two dumbbells on the floor, shoulder-width apart.',
      'Grip the dumbbells and get into a high plank position.',
      'Feet wide for stability.',
      'Row the right dumbbell to your hip while balancing on the left.',
      'Lower it. Row the left.',
      'Keep your hips completely still throughout.',
    ],
    tips: [
      'Wider feet = more stability. Start wide.',
      'Don\'t rotate your hips — that\'s the hard part.',
      'Use hex dumbbells so they don\'t roll.',
    ],
    breathe: 'Exhale on each row. Inhale between.',
  },
  {
    id: 'band-pull-aparts',
    name: 'Band Pull-Aparts',
    duration: 40,
    intensity: 5,
    muscle: 'Back',
    icon: '💪',
    equipment: 'band',
    category: 'strength',
    description: 'Hold band at chest height, pull apart squeezing shoulder blades.',
    easierSwap: 'bird-dogs',
    harderSwap: 'band-rows',
    steps: [
      'Hold a resistance band at chest height with both hands, arms extended.',
      'Grip about shoulder-width apart.',
      'Pull the band apart by squeezing your shoulder blades together.',
      'Stretch until the band touches your chest.',
      'Slowly return to start.',
    ],
    tips: [
      'Keep your arms straight (slight bend in elbows).',
      'Squeeze your upper back hard at full extension.',
      'Great for posture — do these daily.',
    ],
    breathe: 'Exhale as you pull apart. Inhale as you return.',
  },
  {
    id: 'band-rows',
    name: 'Band Rows',
    duration: 40,
    intensity: 7,
    muscle: 'Back',
    icon: '💪',
    equipment: 'band',
    category: 'strength',
    description: 'Anchor band at waist height, pull toward you squeezing back.',
    easierSwap: 'band-pull-aparts',
    harderSwap: null,
    steps: [
      'Anchor the band around a door handle or sturdy post at waist height.',
      'Step back until the band has tension.',
      'Hold both handles with arms extended.',
      'Pull the handles toward your lower ribs, squeezing shoulder blades together.',
      'Slowly extend back out.',
    ],
    tips: [
      'Lead with your elbows, not your hands.',
      'Keep your torso still — don\'t lean back to pull.',
      'Squeeze for a second at the end of each pull.',
    ],
    breathe: 'Exhale as you pull. Inhale as you extend.',
  },

  // ================================================================
  //  SHOULDERS
  // ================================================================
  {
    id: 'pike-push-ups',
    name: 'Pike Push-Ups',
    duration: 35,
    intensity: 8,
    muscle: 'Shoulders',
    icon: '🔺',
    equipment: 'none',
    category: 'strength',
    description: 'Downward dog position, bend elbows to lower head toward floor.',
    easierSwap: 'arm-circles',
    harderSwap: 'elevated-pike-push-ups',
    steps: [
      'Start in a downward dog position — hips high, body forming an inverted V.',
      'Hands slightly wider than shoulder-width.',
      'Bend your elbows and lower the top of your head toward the floor.',
      'Your elbows should flare out to the sides.',
      'Push back up to the starting V position.',
    ],
    tips: [
      'The closer your feet are to your hands, the harder it is.',
      'Look between your hands at the bottom, not forward.',
      'This is the progression toward handstand push-ups.',
    ],
    breathe: 'Inhale as you lower. Exhale as you press up.',
  },
  {
    id: 'arm-circles',
    name: 'Arm Circles',
    duration: 40,
    intensity: 3,
    muscle: 'Shoulders',
    icon: '🔺',
    equipment: 'none',
    category: 'strength',
    description: 'Extend arms and make circles. Small forward, then large backward.',
    easierSwap: null,
    harderSwap: 'pike-push-ups',
    steps: [
      'Stand with feet shoulder-width apart, arms extended to the sides.',
      'Make small forward circles for 15 seconds.',
      'Gradually increase the circle size.',
      'Reverse direction — make backward circles for 15 seconds.',
      'Finish with large, sweeping circles.',
    ],
    tips: [
      'Keep your arms at shoulder height — don\'t let them drop.',
      'This burns more than you\'d expect.',
      'Great warm-up for any upper body work.',
    ],
    breathe: 'Breathe naturally throughout.',
  },
  {
    id: 'elevated-pike-push-ups',
    name: 'Elevated Pike Push-Ups',
    duration: 35,
    intensity: 9,
    muscle: 'Shoulders',
    icon: '🔺',
    equipment: 'chair',
    category: 'strength',
    description: 'Pike push-ups with feet on a chair. Closer to handstand push-ups.',
    easierSwap: 'pike-push-ups',
    harderSwap: null,
    steps: [
      'Place your feet on a chair or sturdy surface.',
      'Walk your hands back toward the chair until your hips are high.',
      'Your body should be in a steep inverted V.',
      'Bend elbows and lower your head toward the floor.',
      'Push back up.',
    ],
    tips: [
      'Make sure the chair is against a wall so it doesn\'t slide.',
      'The steeper the angle, the more shoulder work.',
      'Only do this if you can do 8+ pike push-ups from the floor.',
    ],
    breathe: 'Inhale down. Exhale up.',
  },
  {
    id: 'lateral-raises',
    name: 'Lateral Raises',
    duration: 40,
    intensity: 6,
    muscle: 'Shoulders',
    icon: '🔺',
    equipment: 'dumbbell',
    category: 'strength',
    description: 'Raise dumbbells out to your sides until shoulder height.',
    easierSwap: 'arm-circles',
    harderSwap: 'arnold-press',
    steps: [
      'Stand with dumbbells at your sides, palms facing in.',
      'Slight bend in your elbows.',
      'Raise both arms out to the sides until shoulder height.',
      'Pause briefly at the top.',
      'Lower slowly back down.',
    ],
    tips: [
      'Don\'t swing or use momentum — if you have to, go lighter.',
      'Lead with your elbows, not your hands.',
      'Slight forward lean is okay and can feel better on your shoulders.',
    ],
    breathe: 'Exhale as you raise. Inhale as you lower.',
  },
  {
    id: 'arnold-press',
    name: 'Arnold Press',
    duration: 40,
    intensity: 8,
    muscle: 'Shoulders',
    icon: '🔺',
    equipment: 'dumbbell',
    category: 'strength',
    description: 'Start with palms facing you, rotate and press overhead.',
    easierSwap: 'lateral-raises',
    harderSwap: null,
    steps: [
      'Hold dumbbells at shoulder height with palms facing you (like the top of a curl).',
      'As you press up, rotate your palms to face forward.',
      'Fully extend arms overhead.',
      'Reverse the motion — rotate palms back toward you as you lower.',
    ],
    tips: [
      'The rotation should be smooth and continuous throughout the press.',
      'Don\'t arch your back — brace your core.',
      'Named after Arnold Schwarzenegger — hit all three delt heads in one move.',
    ],
    breathe: 'Exhale as you press up. Inhale as you lower and rotate back.',
  },
  {
    id: 'band-shoulder-press',
    name: 'Band Shoulder Press',
    duration: 40,
    intensity: 6,
    muscle: 'Shoulders',
    icon: '🔺',
    equipment: 'band',
    category: 'strength',
    description: 'Stand on band, press handles overhead.',
    easierSwap: 'arm-circles',
    harderSwap: null,
    steps: [
      'Stand on the middle of the band with both feet.',
      'Hold the handles at shoulder height, palms facing forward.',
      'Press both handles straight up overhead.',
      'Fully extend your arms.',
      'Lower back to shoulder height with control.',
    ],
    tips: [
      'The wider your feet on the band, the more resistance.',
      'Keep your core tight — don\'t arch your back.',
      'Control the negative — don\'t let the band snap your arms down.',
    ],
    breathe: 'Exhale as you press. Inhale as you lower.',
  },

  // ================================================================
  //  GLUTES
  // ================================================================
  {
    id: 'glute-bridges',
    name: 'Glute Bridges',
    duration: 45,
    intensity: 5,
    muscle: 'Glutes',
    icon: '🍑',
    equipment: 'none',
    category: 'strength',
    description: 'Lie on your back, drive hips up, squeeze glutes at the top.',
    easierSwap: null,
    harderSwap: 'single-leg-bridges',
    steps: [
      'Lie on your back, knees bent, feet flat on the floor hip-width apart.',
      'Arms at your sides, palms down.',
      'Drive through your heels to lift your hips toward the ceiling.',
      'Squeeze your glutes HARD at the top.',
      'Your body should form a straight line from shoulders to knees.',
      'Lower slowly and repeat.',
    ],
    tips: [
      'Drive through your HEELS, not your toes.',
      'Don\'t hyperextend at the top — stop when your body is in a straight line.',
      'Squeeze for a full 2 seconds at the top for maximum effect.',
    ],
    breathe: 'Exhale as you lift. Inhale as you lower.',
  },
  {
    id: 'single-leg-bridges',
    name: 'Single-Leg Bridges',
    duration: 40,
    intensity: 7,
    muscle: 'Glutes',
    icon: '🍑',
    equipment: 'none',
    category: 'strength',
    description: 'Glute bridge with one leg extended. Twice the burn.',
    easierSwap: 'glute-bridges',
    harderSwap: 'weighted-hip-thrust',
    steps: [
      'Lie on your back, knees bent, feet flat.',
      'Extend one leg straight up toward the ceiling.',
      'Drive through the heel of your planted foot to lift your hips.',
      'Squeeze your glute at the top.',
      'Lower with control.',
      'Complete all reps on one side, then switch.',
    ],
    tips: [
      'Keep your hips level — don\'t let one side drop.',
      'The extended leg stays straight and pointed up.',
      'If too hard, keep the non-working foot hovering just above the floor instead.',
    ],
    breathe: 'Exhale as you lift. Inhale as you lower.',
  },
  {
    id: 'weighted-hip-thrust',
    name: 'Weighted Hip Thrust',
    duration: 45,
    intensity: 8,
    muscle: 'Glutes',
    icon: '🍑',
    equipment: 'dumbbell',
    category: 'strength',
    description: 'Back on a chair, dumbbell on hips, drive up and squeeze.',
    easierSwap: 'single-leg-bridges',
    harderSwap: null,
    steps: [
      'Sit on the floor with your upper back against a sturdy chair or bench.',
      'Place a dumbbell across your hip crease, holding it with both hands.',
      'Feet flat on the floor, shoulder-width apart.',
      'Drive through your heels to lift your hips until your thighs are parallel to the floor.',
      'Squeeze your glutes at the top for 2 seconds.',
      'Lower slowly back down.',
    ],
    tips: [
      'Your chin should tuck slightly at the top — don\'t throw your head back.',
      'Push through your heels. If you feel it in your quads, move your feet further out.',
      'Pad the dumbbell with a towel if it digs into your hips.',
    ],
    breathe: 'Exhale hard at the top. Inhale as you lower.',
  },
  {
    id: 'donkey-kicks',
    name: 'Donkey Kicks',
    duration: 40,
    intensity: 5,
    muscle: 'Glutes',
    icon: '🍑',
    equipment: 'none',
    category: 'strength',
    description: 'On all fours, kick one leg up toward the ceiling.',
    easierSwap: null,
    harderSwap: 'fire-hydrants',
    steps: [
      'Start on all fours — hands under shoulders, knees under hips.',
      'Keep your right knee bent at 90°.',
      'Lift your right leg up, driving your heel toward the ceiling.',
      'Squeeze your glute at the top.',
      'Lower back down without touching the floor.',
      'Complete all reps, then switch legs.',
    ],
    tips: [
      'Don\'t arch your back — keep your core tight and spine neutral.',
      'The movement is small — don\'t kick wildly.',
      'Think about pushing the ceiling with your heel.',
    ],
    breathe: 'Exhale as you kick up. Inhale as you lower.',
  },
  {
    id: 'fire-hydrants',
    name: 'Fire Hydrants',
    duration: 40,
    intensity: 6,
    muscle: 'Glutes',
    icon: '🍑',
    equipment: 'none',
    category: 'strength',
    description: 'On all fours, lift knee out to the side. Targets outer glutes.',
    easierSwap: 'donkey-kicks',
    harderSwap: 'banded-fire-hydrants',
    steps: [
      'Start on all fours.',
      'Keeping your knee bent at 90°, lift your right knee out to the side.',
      'Lift until your thigh is parallel to the floor (or as high as you can).',
      'Hold for a beat at the top.',
      'Lower back down with control.',
      'Complete all reps, then switch sides.',
    ],
    tips: [
      'Keep your hips square — don\'t shift your weight to one side.',
      'Move from the hip, not by tilting your whole body.',
      'This targets the gluteus medius — the side of your butt.',
    ],
    breathe: 'Exhale as you lift out. Inhale as you lower.',
  },
  {
    id: 'banded-fire-hydrants',
    name: 'Banded Fire Hydrants',
    duration: 40,
    intensity: 8,
    muscle: 'Glutes',
    icon: '🍑',
    equipment: 'band',
    category: 'strength',
    description: 'Fire hydrants with a resistance band above your knees.',
    easierSwap: 'fire-hydrants',
    harderSwap: null,
    steps: [
      'Place a resistance band just above your knees.',
      'Get on all fours.',
      'Lift your right knee out to the side against the band resistance.',
      'Squeeze at the top.',
      'Lower with control — don\'t let the band snap you back.',
      'Complete all reps, then switch.',
    ],
    tips: [
      'The band makes the top of the movement much harder.',
      'Fight the band on the way down too — slow and controlled.',
      'Place the band higher above the knees for more comfort.',
    ],
    breathe: 'Exhale as you lift. Inhale as you lower.',
  },

  // ================================================================
  //  ARMS
  // ================================================================
  {
    id: 'tricep-dips',
    name: 'Tricep Dips',
    duration: 35,
    intensity: 6,
    muscle: 'Arms',
    icon: '💪',
    equipment: 'chair',
    category: 'strength',
    description: 'Use a chair or bench. Lower and press up.',
    easierSwap: 'wall-push-ups',
    harderSwap: 'close-grip-push-ups',
    steps: [
      'Sit on the edge of a sturdy chair, hands gripping the edge beside your hips.',
      'Walk your feet forward and slide your butt off the chair.',
      'Arms straight, supporting your weight.',
      'Bend your elbows to lower your body — go until elbows are at 90°.',
      'Push back up by straightening your arms.',
    ],
    tips: [
      'Keep your back close to the chair — don\'t drift forward.',
      'Bend your knees with feet flat for easier version. Extend legs straight for harder.',
      'Don\'t go below 90° at the elbow — it strains your shoulders.',
    ],
    breathe: 'Inhale as you lower. Exhale as you push up.',
  },
  {
    id: 'wall-push-ups',
    name: 'Wall Push-Ups',
    duration: 35,
    intensity: 2,
    muscle: 'Arms',
    icon: '💪',
    equipment: 'wall',
    category: 'strength',
    description: 'Push-ups against a wall. Great for beginners.',
    easierSwap: null,
    harderSwap: 'knee-push-ups',
    steps: [
      'Stand facing a wall, about arm\'s length away.',
      'Place your hands on the wall at chest height, slightly wider than shoulders.',
      'Lean forward, bending your elbows.',
      'Lower your chest toward the wall.',
      'Push back to the starting position.',
    ],
    tips: [
      'The further your feet from the wall, the harder it gets.',
      'Keep your body in a straight line — don\'t bend at the hips.',
      'This builds toward knee push-ups and full push-ups.',
    ],
    breathe: 'Inhale as you lean in. Exhale as you push away.',
  },
  {
    id: 'close-grip-push-ups',
    name: 'Close-Grip Push-Ups',
    duration: 35,
    intensity: 8,
    muscle: 'Arms',
    icon: '💪',
    equipment: 'none',
    category: 'strength',
    description: 'Push-ups with hands close together.',
    easierSwap: 'tricep-dips',
    harderSwap: null,
    steps: [
      'Start in a push-up position.',
      'Move your hands in so they\'re directly under your shoulders or closer.',
      'Keep your elbows tucked tight to your body.',
      'Lower your chest to the floor.',
      'Push back up, squeezing your triceps.',
    ],
    tips: [
      'Elbows stay close to your ribs — don\'t flare them.',
      'You won\'t go as low as a regular push-up, and that\'s fine.',
      'If it hurts your wrists, widen slightly or use push-up handles.',
    ],
    breathe: 'Inhale down. Exhale up.',
  },
  {
    id: 'bicep-curls',
    name: 'Bicep Curls',
    duration: 40,
    intensity: 5,
    muscle: 'Arms',
    icon: '💪',
    equipment: 'dumbbell',
    category: 'strength',
    description: 'Curl dumbbells up, squeeze at the top, lower slowly.',
    easierSwap: null,
    harderSwap: 'hammer-curls',
    steps: [
      'Stand with dumbbells at your sides, palms facing forward.',
      'Keep your elbows pinned to your sides.',
      'Curl the dumbbells up toward your shoulders.',
      'Squeeze your biceps hard at the top.',
      'Lower slowly — take 2-3 seconds on the way down.',
    ],
    tips: [
      'Don\'t swing your body — if you have to, the weight is too heavy.',
      'The slow lowering (eccentric) is where the muscle grows.',
      'Keep your wrists straight, don\'t curl them.',
    ],
    breathe: 'Exhale as you curl up. Inhale as you lower.',
  },
  {
    id: 'hammer-curls',
    name: 'Hammer Curls',
    duration: 40,
    intensity: 6,
    muscle: 'Arms',
    icon: '💪',
    equipment: 'dumbbell',
    category: 'strength',
    description: 'Curl with palms facing each other. Hits forearms too.',
    easierSwap: 'bicep-curls',
    harderSwap: null,
    steps: [
      'Stand with dumbbells at your sides, palms facing each other (neutral grip).',
      'Keep your elbows pinned to your sides.',
      'Curl both dumbbells up, keeping palms facing inward.',
      'Squeeze at the top.',
      'Lower with control.',
    ],
    tips: [
      'The neutral grip targets the brachialis and forearms more.',
      'You can usually go slightly heavier than regular curls.',
      'Alternate arms or curl together — both work.',
    ],
    breathe: 'Exhale as you curl. Inhale as you lower.',
  },
  {
    id: 'overhead-tricep-ext',
    name: 'Overhead Tricep Extension',
    duration: 40,
    intensity: 6,
    muscle: 'Arms',
    icon: '💪',
    equipment: 'dumbbell',
    category: 'strength',
    description: 'Hold dumbbell overhead with both hands, lower behind head, press up.',
    easierSwap: 'tricep-dips',
    harderSwap: null,
    steps: [
      'Hold one dumbbell with both hands, gripping the top end.',
      'Press it overhead, arms fully extended.',
      'Keeping your upper arms still, bend your elbows to lower the weight behind your head.',
      'Lower until your forearms are parallel to the floor (or slightly past).',
      'Extend back up, squeezing your triceps.',
    ],
    tips: [
      'Keep your elbows pointing forward, not flaring out.',
      'Only your forearms should move — upper arms stay vertical.',
      'Engage your core to avoid arching your back.',
    ],
    breathe: 'Inhale as you lower behind your head. Exhale as you press up.',
  },
  {
    id: 'band-bicep-curls',
    name: 'Band Bicep Curls',
    duration: 40,
    intensity: 5,
    muscle: 'Arms',
    icon: '💪',
    equipment: 'band',
    category: 'strength',
    description: 'Stand on band, curl handles toward shoulders.',
    easierSwap: null,
    harderSwap: null,
    steps: [
      'Stand on the center of the band with both feet.',
      'Hold the handles with palms facing forward.',
      'Keep your elbows pinned to your sides.',
      'Curl the handles up toward your shoulders.',
      'Squeeze at the top, then lower with control.',
    ],
    tips: [
      'Wider stance on the band = more resistance.',
      'The band gets harder at the top, so squeeze extra hard there.',
      'Don\'t let the band snap you down — control the negative.',
    ],
    breathe: 'Exhale as you curl. Inhale as you lower.',
  },

  // ================================================================
  //  FULL BODY
  // ================================================================
  {
    id: 'burpees',
    name: 'Burpees',
    duration: 45,
    intensity: 10,
    muscle: 'Full Body',
    icon: '🫀',
    equipment: 'none',
    category: 'strength',
    description: 'Squat, jump back to plank, push-up, jump up.',
    easierSwap: 'step-back-burpees',
    harderSwap: null,
    steps: [
      'Stand with feet shoulder-width apart.',
      'Squat down and place your hands on the floor.',
      'Jump your feet back into a plank position.',
      'Do a push-up (optional but recommended).',
      'Jump your feet forward to your hands.',
      'Explode upward into a jump, reaching arms overhead.',
    ],
    tips: [
      'The push-up is optional for beginners — just do the plank.',
      'Land softly on each jump.',
      'Pace yourself — 10 good burpees beat 20 sloppy ones.',
    ],
    breathe: 'Exhale on the jump up. Inhale on the way down.',
  },
  {
    id: 'step-back-burpees',
    name: 'Step-Back Burpees',
    duration: 45,
    intensity: 7,
    muscle: 'Full Body',
    icon: '🫀',
    equipment: 'none',
    category: 'strength',
    description: 'Burpees but step back instead of jumping.',
    easierSwap: 'bodyweight-squats',
    harderSwap: 'burpees',
    steps: [
      'Stand with feet shoulder-width apart.',
      'Squat down and place your hands on the floor.',
      'Step one foot back, then the other into plank position.',
      'Do a push-up (optional).',
      'Step one foot forward, then the other.',
      'Stand up and reach arms overhead (no jump needed).',
    ],
    tips: [
      'This is a great way to build toward full burpees.',
      'Still works everything — just lower impact.',
      'Add the jump at the top when you\'re ready to progress.',
    ],
    breathe: 'Exhale as you stand up. Inhale as you go down.',
  },
  {
    id: 'bear-crawls',
    name: 'Bear Crawls',
    duration: 30,
    intensity: 8,
    muscle: 'Full Body',
    icon: '🐻',
    equipment: 'none',
    category: 'strength',
    description: 'Crawl forward on hands and toes, knees hovering off the ground.',
    easierSwap: 'step-back-burpees',
    harderSwap: 'burpees',
    steps: [
      'Start on all fours.',
      'Lift your knees 1-2 inches off the ground.',
      'Move your right hand and left foot forward simultaneously.',
      'Then left hand and right foot.',
      'Keep your knees hovering and your back flat.',
      'Crawl forward, then backward if space is limited.',
    ],
    tips: [
      'Keep your hips low — don\'t let your butt rise up.',
      'Small, controlled steps — not big lunges.',
      'If space is tight, go forward 4 steps and backward 4 steps.',
    ],
    breathe: 'Breathe steadily. Don\'t hold your breath.',
  },
  {
    id: 'inchworms',
    name: 'Inchworms',
    duration: 45,
    intensity: 6,
    muscle: 'Full Body',
    icon: '🐛',
    equipment: 'none',
    category: 'strength',
    description: 'Stand, walk hands out to plank, do a push-up, walk hands back.',
    easierSwap: 'bodyweight-squats',
    harderSwap: 'bear-crawls',
    steps: [
      'Stand tall with feet hip-width apart.',
      'Hinge at the hips and place your hands on the floor.',
      'Walk your hands out to a plank position.',
      'Do a push-up (optional).',
      'Walk your hands back toward your feet.',
      'Stand up and repeat.',
    ],
    tips: [
      'Keep your legs as straight as possible (slight bend is okay).',
      'Don\'t rush — this is a controlled movement.',
      'Great warm-up exercise for any workout.',
    ],
    breathe: 'Inhale in plank. Exhale as you walk hands back and stand.',
  },
  {
    id: 'dumbbell-thrusters',
    name: 'Dumbbell Thrusters',
    duration: 45,
    intensity: 9,
    muscle: 'Full Body',
    icon: '🏋️',
    equipment: 'dumbbell',
    category: 'strength',
    description: 'Front squat with dumbbells, then press overhead as you stand.',
    easierSwap: 'goblet-squats',
    harderSwap: null,
    steps: [
      'Hold dumbbells at shoulder height, palms facing each other.',
      'Squat down — hips back, chest up.',
      'Drive up explosively through your heels.',
      'Use the momentum to press both dumbbells overhead.',
      'Lock out arms at the top.',
      'Lower the dumbbells back to shoulders as you descend into the next squat.',
    ],
    tips: [
      'This should be ONE fluid movement — not a squat, then a press.',
      'Use the squat momentum to help the press.',
      'This is a full-body cardio killer. Pace yourself.',
    ],
    breathe: 'Inhale at the bottom of the squat. Exhale as you drive up and press.',
  },

  // ================================================================
  //  CARDIO
  // ================================================================
  {
    id: 'high-knees',
    name: 'High Knees',
    duration: 30,
    intensity: 8,
    muscle: 'Cardio',
    icon: '🏃',
    equipment: 'none',
    category: 'cardio',
    description: 'Run in place, driving knees as high as possible.',
    easierSwap: 'marching-in-place',
    harderSwap: 'tuck-jumps',
    steps: [
      'Stand with feet hip-width apart.',
      'Drive your right knee up toward your chest.',
      'As it comes down, drive your left knee up.',
      'Pump your arms like you\'re sprinting.',
      'Stay on the balls of your feet.',
    ],
    tips: [
      'Aim for waist height or above with your knees.',
      'Stay tall — don\'t lean forward to meet your knees.',
      'Arms drive the pace — pump them faster to go faster.',
    ],
    breathe: 'Breathe rhythmically — exhale every 2-3 steps.',
  },
  {
    id: 'marching-in-place',
    name: 'Marching in Place',
    duration: 30,
    intensity: 4,
    muscle: 'Cardio',
    icon: '🏃',
    equipment: 'none',
    category: 'cardio',
    description: 'March in place with high knees at a comfortable pace.',
    easierSwap: null,
    harderSwap: 'high-knees',
    steps: [
      'Stand tall with feet together.',
      'Lift your right knee to hip height.',
      'Lower it and lift your left knee.',
      'Swing your arms naturally with each step.',
      'Keep a steady, comfortable pace.',
    ],
    tips: [
      'Great for active recovery or warm-up.',
      'Lift your knees as high as comfortable.',
      'Engage your core as you march.',
    ],
    breathe: 'Breathe naturally and easily.',
  },
  {
    id: 'tuck-jumps',
    name: 'Tuck Jumps',
    duration: 25,
    intensity: 10,
    muscle: 'Cardio',
    icon: '🏃',
    equipment: 'none',
    category: 'cardio',
    description: 'Jump and tuck knees to chest. Maximum intensity.',
    easierSwap: 'high-knees',
    harderSwap: null,
    steps: [
      'Stand with feet shoulder-width apart.',
      'Bend your knees slightly and jump as high as you can.',
      'At the peak, tuck your knees to your chest.',
      'Land softly with bent knees.',
      'Immediately jump again.',
    ],
    tips: [
      'This is extremely intense — short bursts are fine.',
      'Land soft, jump hard.',
      'If your form breaks, switch to high knees.',
    ],
    breathe: 'Sharp exhale on each jump.',
  },
  {
    id: 'jumping-jacks',
    name: 'Jumping Jacks',
    duration: 40,
    intensity: 6,
    muscle: 'Cardio',
    icon: '⭐',
    equipment: 'none',
    category: 'cardio',
    description: 'Classic. Jump feet out and hands overhead, then back.',
    easierSwap: 'half-jacks',
    harderSwap: 'star-jumps',
    steps: [
      'Stand with feet together, arms at your sides.',
      'Jump your feet out wide while raising arms overhead.',
      'Clap or touch hands at the top.',
      'Jump feet back together while lowering arms.',
      'Repeat at a steady rhythm.',
    ],
    tips: [
      'Land softly on the balls of your feet.',
      'Keep a slight bend in your knees throughout.',
      'Full range of motion — arms all the way up.',
    ],
    breathe: 'Inhale as arms go up. Exhale as arms come down.',
  },
  {
    id: 'half-jacks',
    name: 'Half Jacks',
    duration: 40,
    intensity: 3,
    muscle: 'Cardio',
    icon: '⭐',
    equipment: 'none',
    category: 'cardio',
    description: 'Step one foot out at a time instead of jumping. Low impact.',
    easierSwap: null,
    harderSwap: 'jumping-jacks',
    steps: [
      'Stand with feet together, arms at sides.',
      'Step your right foot out while raising arms.',
      'Step it back and lower arms.',
      'Step your left foot out while raising arms.',
      'Continue alternating at a comfortable pace.',
    ],
    tips: [
      'No jumping required — gentle on joints.',
      'Still raise your arms fully for the cardio benefit.',
      'Great modification for jumping jacks.',
    ],
    breathe: 'Breathe naturally with the movement.',
  },
  {
    id: 'star-jumps',
    name: 'Star Jumps',
    duration: 30,
    intensity: 9,
    muscle: 'Cardio',
    icon: '⭐',
    equipment: 'none',
    category: 'cardio',
    description: 'Jump into an X shape — arms and legs spread wide in the air.',
    easierSwap: 'jumping-jacks',
    harderSwap: null,
    steps: [
      'Start in a quarter squat, arms tucked in.',
      'Explode upward.',
      'At the peak, spread arms and legs into an X shape.',
      'Bring everything back in before landing.',
      'Land softly in the starting squat position.',
    ],
    tips: [
      'The bigger the X, the harder the exercise.',
      'Think "expand in the air, compact on landing."',
      'Land as quietly as possible.',
    ],
    breathe: 'Exhale as you jump. Inhale on landing.',
  },
  {
    id: 'skaters',
    name: 'Skaters',
    duration: 35,
    intensity: 7,
    muscle: 'Cardio',
    icon: '⛸️',
    equipment: 'none',
    category: 'cardio',
    description: 'Leap side to side, landing on one foot like a speed skater.',
    easierSwap: 'marching-in-place',
    harderSwap: 'tuck-jumps',
    steps: [
      'Stand on your right foot.',
      'Leap to the left, landing on your left foot.',
      'Swing your right leg behind your left.',
      'Touch your right hand toward your left foot.',
      'Leap back to the right and repeat.',
    ],
    tips: [
      'The wider the leap, the harder the exercise.',
      'Stay low — the more you sink into each landing, the more work.',
      'Use your arms for balance and momentum.',
    ],
    breathe: 'Exhale on each leap.',
  },
  {
    id: 'butt-kicks',
    name: 'Butt Kicks',
    duration: 30,
    intensity: 6,
    muscle: 'Cardio',
    icon: '🏃',
    equipment: 'none',
    category: 'cardio',
    description: 'Run in place, kicking heels up to touch your glutes.',
    easierSwap: 'marching-in-place',
    harderSwap: 'high-knees',
    steps: [
      'Stand with feet hip-width apart.',
      'Jog in place, kicking your heels up behind you.',
      'Try to touch your glutes with each kick.',
      'Pump your arms like running.',
      'Stay on the balls of your feet.',
    ],
    tips: [
      'Stay upright — don\'t lean forward.',
      'Quick, light steps.',
      'This stretches your quads while getting your heart rate up.',
    ],
    breathe: 'Breathe rhythmically with your steps.',
  },
  {
    id: 'jump-rope-imaginary',
    name: 'Jump Rope (No Rope)',
    duration: 40,
    intensity: 7,
    muscle: 'Cardio',
    icon: '🪢',
    equipment: 'none',
    category: 'cardio',
    description: 'Mimic jump rope — light hops, wrists turning. Great cardio.',
    easierSwap: 'half-jacks',
    harderSwap: 'high-knees',
    steps: [
      'Stand with feet together, elbows at your sides.',
      'Make small circular motions with your wrists.',
      'Hop lightly on the balls of your feet.',
      'Keep jumps small — just an inch or two off the ground.',
      'Find a rhythm and maintain it.',
    ],
    tips: [
      'Bounce on the balls of your feet — heels barely touch.',
      'Wrist rotation matters — it engages your forearms.',
      'Mix in single-leg hops and cross-overs for variety.',
    ],
    breathe: 'Breathe steadily and rhythmically.',
  },

  // ================================================================
  //  MOBILITY / WARM-UP
  // ================================================================
  {
    id: 'arm-circles-warmup',
    name: 'Arm Circles',
    duration: 30,
    intensity: 1,
    muscle: 'Shoulders',
    icon: '🔄',
    equipment: 'none',
    category: 'warmup',
    description: 'Small circles forward, then backward. Warms up the shoulders.',
    easierSwap: null,
    harderSwap: null,
    steps: [
      'Extend arms straight out to the sides at shoulder height.',
      'Make small forward circles for 10-15 seconds.',
      'Reverse to backward circles for 10-15 seconds.',
    ],
    tips: ['Keep arms at shoulder height throughout.'],
    breathe: 'Breathe naturally.',
  },
  {
    id: 'leg-swings',
    name: 'Leg Swings',
    duration: 30,
    intensity: 2,
    muscle: 'Legs',
    icon: '🔄',
    equipment: 'none',
    category: 'warmup',
    description: 'Swing one leg forward and back, then side to side. Switch legs.',
    easierSwap: null,
    harderSwap: null,
    steps: [
      'Hold a wall for balance.',
      'Swing your right leg forward and backward like a pendulum.',
      'Do 10 swings, then swing side to side.',
      'Switch legs.',
    ],
    tips: ['Keep your standing leg slightly bent.', 'Start small and increase range gradually.'],
    breathe: 'Breathe naturally.',
  },
  {
    id: 'hip-circles',
    name: 'Hip Circles',
    duration: 30,
    intensity: 1,
    muscle: 'Glutes',
    icon: '🔄',
    equipment: 'none',
    category: 'warmup',
    description: 'Hands on hips, make big circles. Loosen up the hips.',
    easierSwap: null,
    harderSwap: null,
    steps: [
      'Stand with feet shoulder-width apart, hands on hips.',
      'Make large clockwise circles with your hips.',
      'Do 10 circles, then reverse direction.',
    ],
    tips: ['Make the circles as big as comfortable.', 'Keep your feet planted.'],
    breathe: 'Breathe naturally.',
  },
  {
    id: 'worlds-greatest-stretch',
    name: "World's Greatest Stretch",
    duration: 45,
    intensity: 3,
    muscle: 'Full Body',
    icon: '🧘',
    equipment: 'none',
    category: 'warmup',
    description: 'Lunge forward, plant hand, rotate and reach to the sky. Switch sides.',
    easierSwap: null,
    harderSwap: null,
    steps: [
      'Step forward into a deep lunge.',
      'Place your inside hand on the floor next to your front foot.',
      'Rotate your torso and reach your outside arm to the sky.',
      'Hold for a few seconds, feeling the stretch.',
      'Return and switch sides.',
    ],
    tips: ['Go slow and feel the stretch in your hips, thoracic spine, and hamstrings.', 'This one exercise warms up almost everything.'],
    breathe: 'Exhale as you rotate and reach.',
  },
  {
    id: 'high-knee-march',
    name: 'High Knee March',
    duration: 30,
    intensity: 3,
    muscle: 'Cardio',
    icon: '🔄',
    equipment: 'none',
    category: 'warmup',
    description: 'March in place lifting knees high. Easy warm-up pace.',
    easierSwap: null,
    harderSwap: null,
    steps: [
      'Stand tall.',
      'March in place, bringing knees to hip height.',
      'Swing arms naturally.',
      'Keep a steady, comfortable pace.',
    ],
    tips: ['Focus on posture — stay tall.', 'This gets blood flowing without intensity.'],
    breathe: 'Breathe easily and naturally.',
  },
  {
    id: 'torso-twists',
    name: 'Torso Twists',
    duration: 30,
    intensity: 1,
    muscle: 'Core',
    icon: '🔄',
    equipment: 'none',
    category: 'warmup',
    description: 'Feet planted, rotate your upper body side to side. Loosen up.',
    easierSwap: null,
    harderSwap: null,
    steps: [
      'Stand with feet shoulder-width apart.',
      'Arms relaxed at your sides or at chest height.',
      'Rotate your upper body left and right.',
      'Let your arms swing naturally with the rotation.',
    ],
    tips: ['Keep your hips facing forward — only twist from the waist up.', 'Gradually increase the range.'],
    breathe: 'Exhale gently on each twist.',
  },
  {
    id: 'cat-cow',
    name: 'Cat-Cow',
    duration: 40,
    intensity: 2,
    muscle: 'Back',
    icon: '🐈',
    equipment: 'none',
    category: 'warmup',
    description: 'On all fours, arch your back up (cat) then dip it down (cow).',
    easierSwap: null,
    harderSwap: null,
    steps: [
      'Start on all fours — wrists under shoulders, knees under hips.',
      'Cat: Round your back toward the ceiling, tucking chin to chest.',
      'Cow: Arch your back, lifting head and tailbone toward ceiling.',
      'Flow smoothly between the two positions.',
    ],
    tips: ['Move with your breath for a meditative effect.', 'Don\'t rush — feel each vertebra moving.'],
    breathe: 'Inhale into cow (arch). Exhale into cat (round).',
  },

  // ================================================================
  //  COOL-DOWN / STRETCHES
  // ================================================================
  {
    id: 'standing-quad-stretch',
    name: 'Standing Quad Stretch',
    duration: 30,
    intensity: 1,
    muscle: 'Legs',
    icon: '🧘',
    equipment: 'none',
    category: 'cooldown',
    description: 'Stand on one leg, pull the other foot to your glutes. Hold.',
    easierSwap: null,
    harderSwap: null,
    steps: [
      'Stand on one leg (hold a wall for balance if needed).',
      'Grab your other foot behind you and pull it toward your glute.',
      'Keep your knees close together.',
      'Hold for 15 seconds, then switch legs.',
    ],
    tips: ['Stand tall — don\'t lean forward.', 'Push your hips slightly forward for a deeper stretch.'],
    breathe: 'Breathe slowly and deeply throughout.',
  },
  {
    id: 'standing-hamstring-stretch',
    name: 'Hamstring Stretch',
    duration: 30,
    intensity: 1,
    muscle: 'Legs',
    icon: '🧘',
    equipment: 'none',
    category: 'cooldown',
    description: 'Extend one leg forward, hinge at the hips. Feel the stretch.',
    easierSwap: null,
    harderSwap: null,
    steps: [
      'Stand with feet hip-width apart.',
      'Extend one leg forward, heel on the ground, toes up.',
      'Hinge at the hips and lean forward slightly.',
      'Feel the stretch in the back of your extended leg.',
      'Hold 15 seconds, switch legs.',
    ],
    tips: ['Keep your back flat, not rounded.', 'Don\'t bounce — hold steady.'],
    breathe: 'Breathe slowly. Deepen the stretch slightly on each exhale.',
  },
  {
    id: 'chest-opener-stretch',
    name: 'Chest Opener',
    duration: 30,
    intensity: 1,
    muscle: 'Chest',
    icon: '🧘',
    equipment: 'none',
    category: 'cooldown',
    description: 'Clasp hands behind your back, lift and open your chest.',
    easierSwap: null,
    harderSwap: null,
    steps: [
      'Stand tall.',
      'Clasp your hands behind your back.',
      'Straighten your arms and gently lift them.',
      'Open your chest and squeeze your shoulder blades together.',
      'Hold for 15-20 seconds.',
    ],
    tips: ['Look slightly upward for a deeper stretch.', 'Great counter-stretch if you sit at a desk.'],
    breathe: 'Breathe deeply into your chest.',
  },
  {
    id: 'seated-forward-fold',
    name: 'Seated Forward Fold',
    duration: 40,
    intensity: 1,
    muscle: 'Back',
    icon: '🧘',
    equipment: 'none',
    category: 'cooldown',
    description: 'Sit with legs extended, reach for your toes. Breathe and relax.',
    easierSwap: null,
    harderSwap: null,
    steps: [
      'Sit on the floor with legs extended in front of you.',
      'Sit tall, then hinge forward from your hips.',
      'Reach for your toes (or shins, or ankles).',
      'Hold and relax into the stretch.',
    ],
    tips: ['Bend your knees slightly if hamstrings are tight.', 'Relax your neck — let your head hang.'],
    breathe: 'Inhale to lengthen your spine. Exhale to fold deeper.',
  },
  {
    id: 'childs-pose',
    name: "Child's Pose",
    duration: 40,
    intensity: 1,
    muscle: 'Back',
    icon: '🧘',
    equipment: 'none',
    category: 'cooldown',
    description: 'Kneel, sit back on your heels, reach arms forward on the floor.',
    easierSwap: null,
    harderSwap: null,
    steps: [
      'Kneel on the floor, big toes touching.',
      'Sit back on your heels.',
      'Walk your hands forward, lowering your chest toward the floor.',
      'Rest your forehead on the mat.',
      'Relax and hold.',
    ],
    tips: ['Widen your knees for a deeper stretch.', 'This is a resting pose — let everything go.'],
    breathe: 'Breathe slowly and deeply into your back.',
  },
  {
    id: 'figure-four-stretch',
    name: 'Figure-Four Stretch',
    duration: 30,
    intensity: 1,
    muscle: 'Glutes',
    icon: '🧘',
    equipment: 'none',
    category: 'cooldown',
    description: 'Lie on your back, cross ankle over knee, pull thigh toward you.',
    easierSwap: null,
    harderSwap: null,
    steps: [
      'Lie on your back.',
      'Cross your right ankle over your left knee.',
      'Reach through and grab your left thigh.',
      'Pull your left thigh toward your chest.',
      'Feel the stretch in your right glute.',
      'Hold 15 seconds, switch sides.',
    ],
    tips: ['Keep your head on the floor — don\'t strain your neck.', 'Flex the foot of the crossed leg for a deeper stretch.'],
    breathe: 'Breathe deeply. Relax into the stretch on each exhale.',
  },
  {
    id: 'shoulder-cross-stretch',
    name: 'Cross-Body Shoulder Stretch',
    duration: 30,
    intensity: 1,
    muscle: 'Shoulders',
    icon: '🧘',
    equipment: 'none',
    category: 'cooldown',
    description: 'Pull one arm across your chest. Hold 15 seconds each side.',
    easierSwap: null,
    harderSwap: null,
    steps: [
      'Extend your right arm across your chest.',
      'Use your left hand to press your right arm closer to your body.',
      'Feel the stretch in your right shoulder.',
      'Hold 15 seconds, then switch arms.',
    ],
    tips: ['Keep the stretching arm straight.', 'Don\'t shrug your shoulders — keep them relaxed.'],
    breathe: 'Breathe slowly throughout.',
  },
  {
    id: 'deep-breathing',
    name: 'Deep Breathing',
    duration: 45,
    intensity: 1,
    muscle: 'Full Body',
    icon: '🌬️',
    equipment: 'none',
    category: 'cooldown',
    description: 'Breathe in for 4 counts, hold for 4, out for 6. Slow your heart rate.',
    easierSwap: null,
    harderSwap: null,
    steps: [
      'Stand, sit, or lie down comfortably.',
      'Inhale through your nose for 4 counts.',
      'Hold your breath for 4 counts.',
      'Exhale slowly through your mouth for 6 counts.',
      'Repeat 5-6 times.',
    ],
    tips: [
      'Place a hand on your belly — it should rise and fall.',
      'This activates your parasympathetic nervous system.',
      'Great way to end any workout.',
    ],
    breathe: 'Inhale 4 counts, hold 4, exhale 6 counts.',
  },
];

// ============================================================
//  HELPERS
// ============================================================

export function getExerciseById(id) {
  return EXERCISES.find(e => e.id === id) || null;
}

export function getDefaultWorkout() {
  const bases = EXERCISES.filter(
    e => e.category === 'strength' && e.intensity >= 5 && e.intensity <= 8
  );
  const muscles = ['Legs', 'Chest', 'Core', 'Back', 'Shoulders', 'Arms'];
  const workout = [];
  for (const m of muscles) {
    const match = bases.find(e => e.muscle === m && !workout.includes(e));
    if (match) workout.push(match);
  }
  return workout.length >= 6 ? workout : bases.slice(0, 6);
}

export function getRandomSwap(currentWorkoutIds) {
  const candidates = EXERCISES.filter(
    e =>
      e.category === 'strength' &&
      e.intensity >= 4 &&
      e.intensity <= 9 &&
      !currentWorkoutIds.includes(e.id)
  );
  if (candidates.length === 0) return null;
  return candidates[Math.floor(Math.random() * candidates.length)];
}

export function getExercisesByMuscle(muscle) {
  return EXERCISES.filter(e => e.muscle === muscle);
}

export function getExercisesByEquipment(equipment) {
  return EXERCISES.filter(e => e.equipment === equipment);
}

export function getExercisesByCategory(category) {
  return EXERCISES.filter(e => e.category === category);
}

export function getWarmUpExercises() {
  return EXERCISES.filter(e => e.category === 'warmup');
}

export function getCoolDownExercises() {
  return EXERCISES.filter(e => e.category === 'cooldown');
}

export function getAllMuscleGroups() {
  return [...new Set(EXERCISES.map(e => e.muscle))];
}

export function getAllEquipmentTypes() {
  return [...new Set(EXERCISES.map(e => e.equipment))];
}